# Generated by Django 2.0.4 on 2018-06-22 06:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityReportForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(null=True)),
                ('quarter_been_reported', models.CharField(choices=[('Quarter 1', 'Jan - Mar'), ('Quarter 2', 'Apr - Jun'), ('Quarter 3', 'Jul - Oct'), ('Quarter 4', 'Nov - Dec')], max_length=20, verbose_name='quarter being reported')),
                ('name', models.CharField(max_length=50)),
                ('telephone_number', phonenumber_field.modelfields.PhoneNumberField(help_text='0xxxxxxxxx', max_length=128)),
                ('email_address', models.EmailField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Stakeholder Activity Report Form (SARF)',
            },
        ),
        migrations.CreateModel(
            name='CondomProgramming',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condom_dist_point_num', models.PositiveIntegerField(null=True, verbose_name='number')),
                ('activity_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_entry.ActivityReportForm')),
            ],
        ),
        migrations.CreateModel(
            name='CondomProgramming2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('male_condom_distributed_num', models.PositiveIntegerField(null=True, verbose_name='male')),
                ('female_condom_distributed_num', models.PositiveIntegerField(null=True, verbose_name='female')),
                ('activity_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_entry.ActivityReportForm')),
            ],
        ),
        migrations.CreateModel(
            name='DACAValidation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('validation_date', models.DateTimeField(auto_now=True)),
                ('validation_status', models.CharField(choices=[('submitted', 'Submitted'), ('needs_review', 'Needs Review'), ('approved', 'Approved')], max_length=15)),
                ('acknowledgement', models.TextField(default='I acknowledge that I have validated this SARF for data accuracy to the best of my ability. \n                             Any necessary corrections were discussed with the stakeholder prior to this approval. \n                  \n                             Please type your initials below as acknowledgement of the above statement', max_length=1200)),
                ('daca_initials', models.CharField(max_length=5)),
                ('validation_comment', models.TextField(blank=True, max_length=300, null=True)),
                ('activity_form', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data_entry.ActivityReportForm')),
                ('validated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EndOfYearQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funding', models.PositiveIntegerField(verbose_name='How much funding(in kwacha) was spent on HIV &         AIDS activities this year?')),
                ('number_of_meetings_daft', models.PositiveIntegerField(verbose_name='How many DATF meetings did your organisation attend         this year?')),
            ],
        ),
        migrations.CreateModel(
            name='ExperiencedPhysicalViolence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('physical_female_less_10', models.PositiveIntegerField(null=True, verbose_name='female less than 10')),
                ('physical_female_10_14', models.PositiveIntegerField(null=True, verbose_name='female 10 to 14')),
                ('physical_female_15_19', models.PositiveIntegerField(null=True, verbose_name='female 15 to 19')),
                ('physical_female_20_24', models.PositiveIntegerField(null=True, verbose_name='female 20 to 24')),
                ('physical_female_25_plus', models.PositiveIntegerField(null=True, verbose_name='female 25 plus')),
                ('physical_male_less_10', models.PositiveIntegerField(null=True, verbose_name='male less than 10')),
                ('physical_male_10_14', models.PositiveIntegerField(null=True, verbose_name='male 10 to 14')),
                ('physical_male_15_19', models.PositiveIntegerField(null=True, verbose_name='male 15 to 19')),
                ('physical_male_20_24', models.PositiveIntegerField(null=True, verbose_name='male 20 to 24')),
                ('physical_male_25_plus', models.PositiveIntegerField(null=True, verbose_name='male 25 plus')),
                ('activity_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_entry.ActivityReportForm')),
            ],
        ),
        migrations.CreateModel(
            name='ExperiencedSexualViolence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sexual_female_less_10', models.PositiveIntegerField(null=True, verbose_name='female less than 10')),
                ('sexual_female_10_14', models.PositiveIntegerField(null=True, verbose_name='female 10 to 14')),
                ('sexual_female_15_19', models.PositiveIntegerField(null=True, verbose_name='female 15 to 19')),
                ('sexual_female_20_24', models.PositiveIntegerField(null=True, verbose_name='female 20 to 24')),
                ('sexual_female_25_plus', models.PositiveIntegerField(null=True, verbose_name='female 25 plus')),
                ('sexual_male_less_10', models.PositiveIntegerField(null=True, verbose_name='male less than 10')),
                ('sexual_male_10_14', models.PositiveIntegerField(null=True, verbose_name='male 10 to 14')),
                ('sexual_male_15_19', models.PositiveIntegerField(null=True, verbose_name='male 15 to 19')),
                ('sexual_male_20_24', models.PositiveIntegerField(null=True, verbose_name='male 20 to 24')),
                ('sexual_male_25_plus', models.PositiveIntegerField(null=True, verbose_name='male 25 plus')),
                ('activity_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_entry.ActivityReportForm')),
            ],
        ),
        migrations.CreateModel(
            name='FundingSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_organisation', models.CharField(default='', max_length=100)),
                ('funding_amount', models.PositiveIntegerField(verbose_name='Funding Amount(In Zambian Kwacha)')),
            ],
        ),
        migrations.CreateModel(
            name='GeneralComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('general_comment', models.TextField(blank=True, verbose_name='additional comments')),
            ],
            options={
                'verbose_name': 'additional comment',
            },
        ),
        migrations.CreateModel(
            name='GeneralComment2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('general_comment', models.TextField(blank=True, verbose_name='additional comment')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_entry.ActivityReportForm')),
            ],
            options={
                'verbose_name': 'additional comment',
            },
        ),
        migrations.CreateModel(
            name='IECMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_type', models.CharField(choices=[('Books', 'Books'), ('Billboards', 'Billboards'), ('Brochures', 'Brochures'), ('Drama', 'Drama'), ('E spot', 'E spot'), ('Posters', 'Posters'), ('Radio Spots', 'Radio Spots'), ('TV Spots', 'TV Spots'), ('T-Shirts', 'T-Shirts'), ('Other', 'Other')], max_length=100, verbose_name='type of IEC material')),
                ('number_distributed', models.PositiveIntegerField(null=True, verbose_name='number distributed')),
                ('localized', models.BooleanField(default=False, verbose_name='number localised')),
                ('activity_form', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data_entry.ActivityReportForm')),
            ],
        ),
        migrations.CreateModel(
            name='IECMaterial2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_form', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data_entry.ActivityReportForm')),
            ],
        ),
        migrations.CreateModel(
            name='IndividualCurrentlyEnrolled',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('individuals_enrolled_female_10_14', models.PositiveIntegerField(null=True, verbose_name='female 10 to 14')),
                ('individuals_enrolled_female_15_19', models.PositiveIntegerField(null=True, verbose_name='female 15 to 19')),
                ('individuals_enrolled_female_20_24', models.PositiveIntegerField(null=True, verbose_name='female 20 to 24')),
                ('individuals_enrolled_female_25_plus', models.PositiveIntegerField(null=True, verbose_name='female 25 plus')),
                ('individuals_enrolled_male_10_14', models.PositiveIntegerField(null=True, verbose_name='male 10 to 14')),
                ('individuals_enrolled_male_15_19', models.PositiveIntegerField(null=True, verbose_name='male 15 to 19')),
                ('individuals_enrolled_male_20_24', models.PositiveIntegerField(null=True, verbose_name='male 20 to 24')),
                ('individuals_enrolled_male_25_plus', models.PositiveIntegerField(null=True, verbose_name='male 25 plus')),
                ('activity_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_entry.ActivityReportForm')),
            ],
        ),
        migrations.CreateModel(
            name='Inmate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inmates_male_num', models.PositiveIntegerField(null=True, verbose_name='male')),
                ('inmates_female_num', models.PositiveIntegerField(null=True, verbose_name='female')),
                ('activity_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_entry.ActivityReportForm')),
            ],
        ),
        migrations.CreateModel(
            name='MenWithMen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('men_with_men', models.PositiveIntegerField(null=True, verbose_name='number')),
                ('activity_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_entry.ActivityReportForm')),
            ],
        ),
        migrations.CreateModel(
            name='MobilePopulation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_form', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data_entry.ActivityReportForm')),
            ],
        ),
        migrations.CreateModel(
            name='MobilePopulationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_population_type', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MobileWorker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_workers_male_num', models.PositiveIntegerField(null=True, verbose_name='male')),
                ('mobile_workers_female_num', models.PositiveIntegerField(null=True, verbose_name='female')),
                ('activity_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_entry.ActivityReportForm')),
            ],
        ),
        migrations.CreateModel(
            name='NationalOrganisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation_name', models.CharField(max_length=200)),
                ('organisation_address', models.CharField(max_length=100, verbose_name='address of the organisation')),
                ('organisation_contact_email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'parent organisation',
            },
        ),
        migrations.CreateModel(
            name='OrganisationTarget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation_target_option', models.CharField(default='', max_length=100, verbose_name='organisation target group')),
            ],
        ),
        migrations.CreateModel(
            name='OrganisationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation_type_option', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OtherQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_plan', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=100, verbose_name='Does you organisation have a current HIV and         AIDS action plan?')),
                ('workplace_programme', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=20, verbose_name='Does your organisation have a current         and active HIV and AIDS workplace programme?')),
                ('m_and_person', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=20, verbose_name='Does your organisation have a designated M and E person?')),
            ],
        ),
        migrations.CreateModel(
            name='OutOfSchool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('out_school_female_10_14', models.PositiveIntegerField(null=True, verbose_name='female 10 to 14')),
                ('out_school_female_15_19', models.PositiveIntegerField(null=True, verbose_name='female 15 to 19')),
                ('out_school_female_20_24', models.PositiveIntegerField(null=True, verbose_name='female 20 to 24')),
                ('out_school_male_10_14', models.PositiveIntegerField(null=True, verbose_name='male 10 to 14')),
                ('out_school_male_15_19', models.PositiveIntegerField(null=True, verbose_name='male 15 to 19')),
                ('out_school_male_20_24', models.PositiveIntegerField(null=True, verbose_name='male 20 to 24')),
                ('activity_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_entry.ActivityReportForm')),
            ],
        ),
        migrations.CreateModel(
            name='PeopleWhoInjectDrug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pwid_male', models.PositiveIntegerField(null=True, verbose_name='male')),
                ('pwid_female', models.PositiveIntegerField(null=True, verbose_name='female')),
                ('activity_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_entry.ActivityReportForm')),
            ],
        ),
        migrations.CreateModel(
            name='PersonsWithDisabilty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pwd_male_num', models.PositiveIntegerField(null=True, verbose_name='males')),
                ('pwd_female_num', models.PositiveIntegerField(null=True, verbose_name='females')),
                ('activity_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_entry.ActivityReportForm')),
            ],
        ),
        migrations.CreateModel(
            name='PostExposureProphylaxis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessed_pep_female_less_10', models.PositiveIntegerField(null=True, verbose_name='female less than 10')),
                ('accessed_pep_female_10_14', models.PositiveIntegerField(null=True, verbose_name='female 10 to 14')),
                ('accessed_pep_female_15_19', models.PositiveIntegerField(null=True, verbose_name='female 15 to 19')),
                ('accessed_pep_female_20_24', models.PositiveIntegerField(null=True, verbose_name='female 20 to 24')),
                ('accessed_pep_female_25_plus', models.PositiveIntegerField(null=True, verbose_name='female 25 plus')),
                ('accessed_pep_male_less_10', models.PositiveIntegerField(null=True, verbose_name='male less than 10')),
                ('accessed_pep_male_10_14', models.PositiveIntegerField(null=True, verbose_name='male 10 to 14')),
                ('accessed_pep_male_15_19', models.PositiveIntegerField(null=True, verbose_name='male 15 to 19')),
                ('accessed_pep_male_20_24', models.PositiveIntegerField(null=True, verbose_name='male 20 to 24')),
                ('accessed_pep_male_25_plus', models.PositiveIntegerField(null=True, verbose_name='male 25 plus')),
                ('activity_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_entry.ActivityReportForm')),
            ],
        ),
        migrations.CreateModel(
            name='PreExposureProphylaxis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referred_pep_female_15_19', models.PositiveIntegerField(null=True, verbose_name='female 15 to 19')),
                ('referred_pep_female_20_24', models.PositiveIntegerField(null=True, verbose_name='female 20 to 24')),
                ('referred_pep_female_25_plus', models.PositiveIntegerField(null=True, verbose_name='female 25 plus')),
                ('referred_pep_male_15_19', models.PositiveIntegerField(null=True, verbose_name='male 15 to 19')),
                ('referred_pep_male_20_24', models.PositiveIntegerField(null=True, verbose_name='male 20 to 24')),
                ('referred_pep_male_25_plus', models.PositiveIntegerField(null=True, verbose_name='male 25 plus')),
                ('activity_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_entry.ActivityReportForm')),
            ],
        ),
        migrations.CreateModel(
            name='ProgramActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReportedCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reported_female_less_10', models.PositiveIntegerField(null=True, verbose_name='female less than 10')),
                ('reported_female_10_14', models.PositiveIntegerField(null=True, verbose_name='female 10 to 14')),
                ('reported_female_15_19', models.PositiveIntegerField(null=True, verbose_name='female 15 to 19')),
                ('reported_female_20_24', models.PositiveIntegerField(null=True, verbose_name='female 20 to 24')),
                ('reported_female_25_plus', models.PositiveIntegerField(null=True, verbose_name='female 25 plus')),
                ('reported_male_less_10', models.PositiveIntegerField(null=True, verbose_name='male less than 10')),
                ('reported_male_10_14', models.PositiveIntegerField(null=True, verbose_name='male 10 to 14')),
                ('reported_male_15_19', models.PositiveIntegerField(null=True, verbose_name='male 15 to 19')),
                ('reported_male_20_24', models.PositiveIntegerField(null=True, verbose_name='male 20 to 24')),
                ('reported_male_25_plus', models.PositiveIntegerField(null=True, verbose_name='male 25 plus')),
                ('activity_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_entry.ActivityReportForm')),
            ],
        ),
        migrations.CreateModel(
            name='SexWorker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex_workers_female_10_14', models.PositiveIntegerField(null=True, verbose_name='female 10 to 14')),
                ('sex_workers_female_15_19', models.PositiveIntegerField(null=True, verbose_name='female 15 to 19')),
                ('sex_workers_female_20_24', models.PositiveIntegerField(null=True, verbose_name='female 20 to 24')),
                ('sex_workers_female_25_29', models.PositiveIntegerField(null=True, verbose_name='female 25 to 29')),
                ('sex_workers_female_30_34', models.PositiveIntegerField(null=True, verbose_name='female 30 to 34')),
                ('sex_workers_female_35_plus', models.PositiveIntegerField(null=True, verbose_name='female 35 plus')),
                ('sex_workers_male_10_14', models.PositiveIntegerField(null=True, verbose_name='male 10 to 14')),
                ('sex_workers_male_15_19', models.PositiveIntegerField(null=True, verbose_name='male 15 to 19')),
                ('sex_workers_male_20_24', models.PositiveIntegerField(null=True, verbose_name='male 20 to 24')),
                ('sex_workers_male_25_29', models.PositiveIntegerField(null=True, verbose_name='male 25 to 29')),
                ('sex_workers_male_30_34', models.PositiveIntegerField(null=True, verbose_name='male 30 to 34')),
                ('sex_workers_male_35_plus', models.PositiveIntegerField(null=True, verbose_name='male 35 plus')),
                ('activity_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_entry.ActivityReportForm')),
            ],
        ),
        migrations.CreateModel(
            name='SourcesOfInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StakeholderDirectory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation', models.CharField(help_text='If organisation/project name is the same as         parent organisation. Please re-enter the same name', max_length=200, verbose_name='organisation/project')),
                ('organisation_address', models.CharField(blank=True, max_length=100, null=True, verbose_name='address of the organisation')),
                ('start_year', models.DateField(verbose_name='which year did your organisation start working in this district?')),
                ('gps', models.CharField(blank=True, help_text='use decimal degrees format(ie: -15.38753, 28.32282)', max_length=20, verbose_name='GPS Coordinates')),
                ('website', models.URLField(blank=True)),
                ('description_of_organisation', models.TextField(max_length=1200, verbose_name='Brief description of the organisation (Please describe your         organisation in no more than 250 words)')),
                ('key_contact_name', models.CharField(max_length=50, verbose_name='name of key contact person')),
                ('position_within_organisation', models.CharField(max_length=50, verbose_name='position within the organisation')),
                ('telephone_number', phonenumber_field.modelfields.PhoneNumberField(help_text='09xxxxxxxx', max_length=128)),
                ('telephone_number_alternative', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='09xxxxxxxx', max_length=128)),
                ('email_address', models.EmailField(max_length=254, verbose_name='email address')),
                ('permanent_employee_female', models.PositiveIntegerField(null=True, verbose_name='current number of permanent female employees')),
                ('permanent_employee_male', models.PositiveIntegerField(null=True, verbose_name='current number of permanent male employees')),
                ('temporary_employee_female', models.PositiveIntegerField(null=True, verbose_name='current number of temporary female employees')),
                ('temporary_employee_male', models.PositiveIntegerField(null=True, verbose_name='current number of temporary male employees')),
                ('volunteer_employee_female', models.PositiveIntegerField(null=True, verbose_name='current number of volunteer female employees')),
                ('volunteer_employee_male', models.PositiveIntegerField(null=True, verbose_name='current number of volunteer male employees')),
                ('organisation_type', models.CharField(choices=[('Community Based Organisation', 'Community Based Organisation'), ('Faith Based Organisation', 'Faith Based Organisation'), ('Government Organisation', 'Government Organisation'), ('International NGO', 'International Non Governmental Organisation'), ('Local NGO', 'Local Non Governmental Organisation'), ('Private Organisation', 'Private Organisation'), ('Other organisation / group - please specify', 'Other organisation / group - please specify')], max_length=100, verbose_name="which of the following 'types' would best describe your         organisation? (Please only tick one type of organisation)")),
                ('national_organisation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data_entry.NationalOrganisation', verbose_name='parent organisation')),
                ('organisation_district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data_entry.District', verbose_name='organisation district')),
                ('organisation_province', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data_entry.Province')),
                ('organisation_targets', models.ManyToManyField(to='data_entry.OrganisationTarget', verbose_name='which group(s) does your organisation target? (please tick as many         different groups that are targeted by your organisation)')),
            ],
            options={
                'verbose_name_plural': 'Stakeholder Directory',
            },
        ),
        migrations.CreateModel(
            name='SupportAndCare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_entry.ActivityReportForm')),
            ],
        ),
        migrations.CreateModel(
            name='SupportField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_of_support', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SupportGroupSetUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('support_groups', models.PositiveIntegerField(null=True, verbose_name='number')),
                ('activity_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_entry.ActivityReportForm')),
            ],
        ),
        migrations.CreateModel(
            name='SynergyDevelopmentSector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employees_reached_male_num', models.PositiveIntegerField(null=True, verbose_name='male')),
                ('employees_reached_female_num', models.PositiveIntegerField(null=True, verbose_name='female')),
                ('activity_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_entry.ActivityReportForm')),
            ],
        ),
        migrations.CreateModel(
            name='TargetGroupPreventionMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prevention_message', models.CharField(choices=[('Condom use', 'Condom use'), ('MC information', 'MC information'), ('MCP information', 'MCP information'), ('PMTCT Promotion', 'PMTCT Promotion'), ('VCT/ HCT Promotion', 'VCT/ HCT Promotion')], max_length=100, null=True)),
                ('organisation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data_entry.StakeholderDirectory')),
                ('target_groups', models.ManyToManyField(to='data_entry.OrganisationTarget')),
            ],
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teachers_female', models.PositiveIntegerField(null=True, verbose_name='female')),
                ('teachers_male', models.PositiveIntegerField(null=True, verbose_name='male')),
                ('activity_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_entry.ActivityReportForm')),
            ],
        ),
        migrations.CreateModel(
            name='TransgenderIndividual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transgender_num', models.PositiveIntegerField(null=True, verbose_name='number')),
                ('activity_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_entry.ActivityReportForm')),
            ],
        ),
        migrations.CreateModel(
            name='TypesOfFundingSupport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('support_option', models.CharField(default='', max_length=100)),
                ('funding_source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data_entry.FundingSource')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data_entry.District')),
                ('national_organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_entry.NationalOrganisation')),
                ('province', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data_entry.Province')),
                ('stakeholder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data_entry.StakeholderDirectory')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VulnerablePeople',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ovc_female_less_10', models.PositiveIntegerField(null=True, verbose_name='female less than 10')),
                ('ovc_female_10_14', models.PositiveIntegerField(null=True, verbose_name='female 10 to 14')),
                ('ovc_female_15_19', models.PositiveIntegerField(null=True, verbose_name='female 15 to 19')),
                ('ovc_female_20_24', models.PositiveIntegerField(null=True, verbose_name='female 20 to 24')),
                ('ovc_female_25_plus', models.PositiveIntegerField(null=True, verbose_name='female 25 plus')),
                ('ovc_male_less_10', models.PositiveIntegerField(null=True, verbose_name='male less than 10')),
                ('ovc_male_10_14', models.PositiveIntegerField(null=True, verbose_name='male 10 to 14')),
                ('ovc_male_15_19', models.PositiveIntegerField(null=True, verbose_name='male 15 to 19')),
                ('ovc_male_20_24', models.PositiveIntegerField(null=True, verbose_name='male 20 to 24')),
                ('ovc_male_25_plus', models.PositiveIntegerField(null=True, verbose_name='male 25 plus')),
                ('activity_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_entry.ActivityReportForm')),
            ],
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data_entry.District')),
            ],
        ),
        migrations.AddField(
            model_name='supportandcare',
            name='type',
            field=models.ManyToManyField(to='data_entry.SupportField', verbose_name='type'),
        ),
        migrations.AddField(
            model_name='programactivity',
            name='areas_of_support',
            field=models.ManyToManyField(to='data_entry.SupportField', verbose_name='Program activities by geographic area'),
        ),
        migrations.AddField(
            model_name='programactivity',
            name='organisation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data_entry.StakeholderDirectory'),
        ),
        migrations.AddField(
            model_name='programactivity',
            name='ward',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data_entry.Ward'),
        ),
        migrations.AddField(
            model_name='otherquestion',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_entry.StakeholderDirectory'),
        ),
        migrations.AddField(
            model_name='mobilepopulation',
            name='mobile_population_types',
            field=models.ManyToManyField(to='data_entry.MobilePopulationType'),
        ),
        migrations.AddField(
            model_name='iecmaterial2',
            name='target_audience',
            field=models.ManyToManyField(to='data_entry.OrganisationTarget'),
        ),
        migrations.AddField(
            model_name='generalcomment',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_entry.StakeholderDirectory'),
        ),
        migrations.AddField(
            model_name='fundingsource',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_entry.StakeholderDirectory'),
        ),
        migrations.AddField(
            model_name='endofyearquestion',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_entry.StakeholderDirectory'),
        ),
        migrations.AddField(
            model_name='district',
            name='province',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data_entry.Province'),
        ),
        migrations.AddField(
            model_name='activityreportform',
            name='stake_holder_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data_entry.StakeholderDirectory', verbose_name='Name of the Organisation'),
        ),
    ]
