# Generated by Django 2.0.4 on 2018-06-20 06:36

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    replaces = [('data_entry', '0002_auto_20180619_2329'), ('data_entry', '0003_auto_20180619_2351'), ('data_entry', '0004_auto_20180620_0003'), ('data_entry', '0005_auto_20180620_0005'), ('data_entry', '0006_auto_20180620_0755'), ('data_entry', '0007_auto_20180620_0757'), ('data_entry', '0008_auto_20180620_0758')]

    dependencies = [
        ('data_entry', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activityreportform',
            options={'verbose_name_plural': 'Stakeholder Activity Report Form (SARF)'},
        ),
        migrations.AlterModelOptions(
            name='nationalorganisation',
            options={'verbose_name': 'parent organisation'},
        ),
        migrations.AlterModelOptions(
            name='stakeholderdirectory',
            options={'verbose_name_plural': 'Stakeholder Directory'},
        ),
        migrations.RemoveField(
            model_name='endofyearquestion',
            name='number_of_meetings_paft',
        ),
        migrations.AlterField(
            model_name='activityreportform',
            name='telephone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='0xxxxxxxxx', max_length=128),
        ),
        migrations.AlterField(
            model_name='fundingsource',
            name='funding_amount',
            field=models.PositiveIntegerField(verbose_name='Funding Amount(In Zambian Kwacha)'),
        ),
        migrations.AlterField(
            model_name='otherquestion',
            name='action_plan',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=100, verbose_name='Does you organisation have a current HIV and         AIDS action plan?'),
        ),
        migrations.AlterField(
            model_name='stakeholderdirectory',
            name='gps',
            field=models.CharField(blank=True, help_text='use decimal degrees format(ie: -15.38753, 28.32282)', max_length=20, verbose_name='GPS Coordinates'),
        ),
        migrations.AlterField(
            model_name='stakeholderdirectory',
            name='national_organisation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data_entry.NationalOrganisation', verbose_name='parent organisation'),
        ),
        migrations.AlterField(
            model_name='stakeholderdirectory',
            name='organisation',
            field=models.CharField(max_length=200, verbose_name='organisation/ project'),
        ),
        migrations.AlterField(
            model_name='stakeholderdirectory',
            name='telephone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='0xxxxxxxxx', max_length=128),
        ),
        migrations.AlterField(
            model_name='stakeholderdirectory',
            name='telephone_number_alternative',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='0xxxxxxxxx', max_length=128),
        ),
        migrations.RemoveField(
            model_name='dacavalidation',
            name='form_validated',
        ),
        migrations.AddField(
            model_name='dacavalidation',
            name='validation_comment',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='dacavalidation',
            name='validation_status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('needs_review', 'Needs Review'), ('approved', 'Approved')], default='submitted', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dacavalidation',
            name='daca_initials',
            field=models.CharField(max_length=5),
        ),
        migrations.AddField(
            model_name='dacavalidation',
            name='acknowledgement',
            field=models.TextField(default='I acknowledge that I have validated this SARF for data accuracy to the best of my ability. \n                             Any necessary corrections were discussed with the stakeholder prior to this approval. \n                  \n                             Please type your initials below as acknowledgement of the above statement', max_length=1200),
        ),
    ]
