# Generated by Django 2.0.5 on 2018-06-12 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condomprogramming',
            name='condom_dist_point_num',
            field=models.PositiveIntegerField(null=True, verbose_name='number'),
        ),
        migrations.AlterField(
            model_name='condomprogramming2',
            name='female_condom_distributed_num',
            field=models.PositiveIntegerField(null=True, verbose_name='female'),
        ),
        migrations.AlterField(
            model_name='condomprogramming2',
            name='male_condom_distributed_num',
            field=models.PositiveIntegerField(null=True, verbose_name='male'),
        ),
        migrations.AlterField(
            model_name='experiencedphysicalviolence',
            name='physical_female_10_14',
            field=models.PositiveIntegerField(null=True, verbose_name='female 10 to 14'),
        ),
        migrations.AlterField(
            model_name='experiencedphysicalviolence',
            name='physical_female_15_19',
            field=models.PositiveIntegerField(null=True, verbose_name='female 15 to 19'),
        ),
        migrations.AlterField(
            model_name='experiencedphysicalviolence',
            name='physical_female_20_24',
            field=models.PositiveIntegerField(null=True, verbose_name='female 20 to 24'),
        ),
        migrations.AlterField(
            model_name='experiencedphysicalviolence',
            name='physical_female_25_plus',
            field=models.PositiveIntegerField(null=True, verbose_name='female 25 plus'),
        ),
        migrations.AlterField(
            model_name='experiencedphysicalviolence',
            name='physical_female_less_10',
            field=models.PositiveIntegerField(null=True, verbose_name='female less than 10'),
        ),
        migrations.AlterField(
            model_name='experiencedphysicalviolence',
            name='physical_male_10_14',
            field=models.PositiveIntegerField(null=True, verbose_name='male 10 to 14'),
        ),
        migrations.AlterField(
            model_name='experiencedphysicalviolence',
            name='physical_male_15_19',
            field=models.PositiveIntegerField(null=True, verbose_name='male 15 to 19'),
        ),
        migrations.AlterField(
            model_name='experiencedphysicalviolence',
            name='physical_male_20_24',
            field=models.PositiveIntegerField(null=True, verbose_name='male 20 to 24'),
        ),
        migrations.AlterField(
            model_name='experiencedphysicalviolence',
            name='physical_male_25_plus',
            field=models.PositiveIntegerField(null=True, verbose_name='male 25 plus'),
        ),
        migrations.AlterField(
            model_name='experiencedphysicalviolence',
            name='physical_male_less_10',
            field=models.PositiveIntegerField(null=True, verbose_name='male less than 10'),
        ),
        migrations.AlterField(
            model_name='experiencedsexualviolence',
            name='sexual_female_10_14',
            field=models.PositiveIntegerField(null=True, verbose_name='female 10 to 14'),
        ),
        migrations.AlterField(
            model_name='experiencedsexualviolence',
            name='sexual_female_15_19',
            field=models.PositiveIntegerField(null=True, verbose_name='female 15 to 19'),
        ),
        migrations.AlterField(
            model_name='experiencedsexualviolence',
            name='sexual_female_20_24',
            field=models.PositiveIntegerField(null=True, verbose_name='female 20 to 24'),
        ),
        migrations.AlterField(
            model_name='experiencedsexualviolence',
            name='sexual_female_25_plus',
            field=models.PositiveIntegerField(null=True, verbose_name='female 25 plus'),
        ),
        migrations.AlterField(
            model_name='experiencedsexualviolence',
            name='sexual_female_less_10',
            field=models.PositiveIntegerField(null=True, verbose_name='female less than 10'),
        ),
        migrations.AlterField(
            model_name='experiencedsexualviolence',
            name='sexual_male_10_14',
            field=models.PositiveIntegerField(null=True, verbose_name='male 10 to 14'),
        ),
        migrations.AlterField(
            model_name='experiencedsexualviolence',
            name='sexual_male_15_19',
            field=models.PositiveIntegerField(null=True, verbose_name='male 15 to 19'),
        ),
        migrations.AlterField(
            model_name='experiencedsexualviolence',
            name='sexual_male_20_24',
            field=models.PositiveIntegerField(null=True, verbose_name='male 20 to 24'),
        ),
        migrations.AlterField(
            model_name='experiencedsexualviolence',
            name='sexual_male_25_plus',
            field=models.PositiveIntegerField(null=True, verbose_name='male 25 plus'),
        ),
        migrations.AlterField(
            model_name='experiencedsexualviolence',
            name='sexual_male_less_10',
            field=models.PositiveIntegerField(null=True, verbose_name='male less than 10'),
        ),
        migrations.AlterField(
            model_name='individualcurrentlyenrolled',
            name='individuals_enrolled_female_10_14',
            field=models.PositiveIntegerField(null=True, verbose_name='female 10 to 14'),
        ),
        migrations.AlterField(
            model_name='individualcurrentlyenrolled',
            name='individuals_enrolled_female_15_19',
            field=models.PositiveIntegerField(null=True, verbose_name='female 15 to 19'),
        ),
        migrations.AlterField(
            model_name='individualcurrentlyenrolled',
            name='individuals_enrolled_female_20_24',
            field=models.PositiveIntegerField(null=True, verbose_name='female 20 to 24'),
        ),
        migrations.AlterField(
            model_name='individualcurrentlyenrolled',
            name='individuals_enrolled_female_25_plus',
            field=models.PositiveIntegerField(null=True, verbose_name='female 25 plus'),
        ),
        migrations.AlterField(
            model_name='individualcurrentlyenrolled',
            name='individuals_enrolled_male_10_14',
            field=models.PositiveIntegerField(null=True, verbose_name='male 10 to 14'),
        ),
        migrations.AlterField(
            model_name='individualcurrentlyenrolled',
            name='individuals_enrolled_male_15_19',
            field=models.PositiveIntegerField(null=True, verbose_name='male 15 to 19'),
        ),
        migrations.AlterField(
            model_name='individualcurrentlyenrolled',
            name='individuals_enrolled_male_20_24',
            field=models.PositiveIntegerField(null=True, verbose_name='male 20 to 24'),
        ),
        migrations.AlterField(
            model_name='individualcurrentlyenrolled',
            name='individuals_enrolled_male_25_plus',
            field=models.PositiveIntegerField(null=True, verbose_name='male 25 plus'),
        ),
        migrations.AlterField(
            model_name='inmate',
            name='inmates_female_num',
            field=models.PositiveIntegerField(null=True, verbose_name='female'),
        ),
        migrations.AlterField(
            model_name='inmate',
            name='inmates_male_num',
            field=models.PositiveIntegerField(null=True, verbose_name='male'),
        ),
        migrations.AlterField(
            model_name='menwithmen',
            name='men_with_men',
            field=models.PositiveIntegerField(null=True, verbose_name='number'),
        ),
        migrations.AlterField(
            model_name='mobileworker',
            name='mobile_workers_female_num',
            field=models.PositiveIntegerField(null=True, verbose_name='female'),
        ),
        migrations.AlterField(
            model_name='mobileworker',
            name='mobile_workers_male_num',
            field=models.PositiveIntegerField(null=True, verbose_name='male'),
        ),
        migrations.AlterField(
            model_name='outofschool',
            name='out_school_female_10_14',
            field=models.PositiveIntegerField(null=True, verbose_name='female 10 to 14'),
        ),
        migrations.AlterField(
            model_name='outofschool',
            name='out_school_female_15_19',
            field=models.PositiveIntegerField(null=True, verbose_name='female 15 to 19'),
        ),
        migrations.AlterField(
            model_name='outofschool',
            name='out_school_female_20_24',
            field=models.PositiveIntegerField(null=True, verbose_name='female 20 to 24'),
        ),
        migrations.AlterField(
            model_name='outofschool',
            name='out_school_male_10_14',
            field=models.PositiveIntegerField(null=True, verbose_name='male 10 to 14'),
        ),
        migrations.AlterField(
            model_name='outofschool',
            name='out_school_male_15_19',
            field=models.PositiveIntegerField(null=True, verbose_name='male 15 to 19'),
        ),
        migrations.AlterField(
            model_name='outofschool',
            name='out_school_male_20_24',
            field=models.PositiveIntegerField(null=True, verbose_name='male 20 to 24'),
        ),
        migrations.AlterField(
            model_name='peoplewhoinjectdrug',
            name='pwid_female',
            field=models.PositiveIntegerField(null=True, verbose_name='female'),
        ),
        migrations.AlterField(
            model_name='peoplewhoinjectdrug',
            name='pwid_male',
            field=models.PositiveIntegerField(null=True, verbose_name='male'),
        ),
        migrations.AlterField(
            model_name='personswithdisabilty',
            name='pwd_female_num',
            field=models.PositiveIntegerField(null=True, verbose_name='females'),
        ),
        migrations.AlterField(
            model_name='personswithdisabilty',
            name='pwd_male_num',
            field=models.PositiveIntegerField(null=True, verbose_name='males'),
        ),
        migrations.AlterField(
            model_name='postexposureprophylaxis',
            name='accessed_pep_female_10_14',
            field=models.PositiveIntegerField(null=True, verbose_name='female 10 to 14'),
        ),
        migrations.AlterField(
            model_name='postexposureprophylaxis',
            name='accessed_pep_female_15_19',
            field=models.PositiveIntegerField(null=True, verbose_name='female 15 to 19'),
        ),
        migrations.AlterField(
            model_name='postexposureprophylaxis',
            name='accessed_pep_female_20_24',
            field=models.PositiveIntegerField(null=True, verbose_name='female 20 to 24'),
        ),
        migrations.AlterField(
            model_name='postexposureprophylaxis',
            name='accessed_pep_female_25_plus',
            field=models.PositiveIntegerField(null=True, verbose_name='female 25 plus'),
        ),
        migrations.AlterField(
            model_name='postexposureprophylaxis',
            name='accessed_pep_female_less_10',
            field=models.PositiveIntegerField(null=True, verbose_name='female less than 10'),
        ),
        migrations.AlterField(
            model_name='postexposureprophylaxis',
            name='accessed_pep_male_10_14',
            field=models.PositiveIntegerField(null=True, verbose_name='male 10 to 14'),
        ),
        migrations.AlterField(
            model_name='postexposureprophylaxis',
            name='accessed_pep_male_15_19',
            field=models.PositiveIntegerField(null=True, verbose_name='male 15 to 19'),
        ),
        migrations.AlterField(
            model_name='postexposureprophylaxis',
            name='accessed_pep_male_20_24',
            field=models.PositiveIntegerField(null=True, verbose_name='male 20 to 24'),
        ),
        migrations.AlterField(
            model_name='postexposureprophylaxis',
            name='accessed_pep_male_25_plus',
            field=models.PositiveIntegerField(null=True, verbose_name='male 25 plus'),
        ),
        migrations.AlterField(
            model_name='postexposureprophylaxis',
            name='accessed_pep_male_less_10',
            field=models.PositiveIntegerField(null=True, verbose_name='male less than 10'),
        ),
        migrations.AlterField(
            model_name='preexposureprophylaxis',
            name='referred_pep_female_15_19',
            field=models.PositiveIntegerField(null=True, verbose_name='female 15 to 19'),
        ),
        migrations.AlterField(
            model_name='preexposureprophylaxis',
            name='referred_pep_female_20_24',
            field=models.PositiveIntegerField(null=True, verbose_name='female 20 to 24'),
        ),
        migrations.AlterField(
            model_name='preexposureprophylaxis',
            name='referred_pep_female_25_plus',
            field=models.PositiveIntegerField(null=True, verbose_name='female 25 plus'),
        ),
        migrations.AlterField(
            model_name='preexposureprophylaxis',
            name='referred_pep_male_15_19',
            field=models.PositiveIntegerField(null=True, verbose_name='male 15 to 19'),
        ),
        migrations.AlterField(
            model_name='preexposureprophylaxis',
            name='referred_pep_male_20_24',
            field=models.PositiveIntegerField(null=True, verbose_name='male 20 to 24'),
        ),
        migrations.AlterField(
            model_name='preexposureprophylaxis',
            name='referred_pep_male_25_plus',
            field=models.PositiveIntegerField(null=True, verbose_name='male 25 plus'),
        ),
        migrations.AlterField(
            model_name='reportedcase',
            name='reported_female_10_14',
            field=models.PositiveIntegerField(null=True, verbose_name='female 10 to 14'),
        ),
        migrations.AlterField(
            model_name='reportedcase',
            name='reported_female_15_19',
            field=models.PositiveIntegerField(null=True, verbose_name='female 15 to 19'),
        ),
        migrations.AlterField(
            model_name='reportedcase',
            name='reported_female_20_24',
            field=models.PositiveIntegerField(null=True, verbose_name='female 20 to 24'),
        ),
        migrations.AlterField(
            model_name='reportedcase',
            name='reported_female_25_plus',
            field=models.PositiveIntegerField(null=True, verbose_name='female 25 plus'),
        ),
        migrations.AlterField(
            model_name='reportedcase',
            name='reported_female_less_10',
            field=models.PositiveIntegerField(null=True, verbose_name='female less than 10'),
        ),
        migrations.AlterField(
            model_name='reportedcase',
            name='reported_male_10_14',
            field=models.PositiveIntegerField(null=True, verbose_name='male 10 to 14'),
        ),
        migrations.AlterField(
            model_name='reportedcase',
            name='reported_male_15_19',
            field=models.PositiveIntegerField(null=True, verbose_name='male 15 to 19'),
        ),
        migrations.AlterField(
            model_name='reportedcase',
            name='reported_male_20_24',
            field=models.PositiveIntegerField(null=True, verbose_name='male 20 to 24'),
        ),
        migrations.AlterField(
            model_name='reportedcase',
            name='reported_male_25_plus',
            field=models.PositiveIntegerField(null=True, verbose_name='male 25 plus'),
        ),
        migrations.AlterField(
            model_name='reportedcase',
            name='reported_male_less_10',
            field=models.PositiveIntegerField(null=True, verbose_name='male less than 10'),
        ),
        migrations.AlterField(
            model_name='sexworker',
            name='sex_workers_female_10_14',
            field=models.PositiveIntegerField(null=True, verbose_name='female 10 to 14'),
        ),
        migrations.AlterField(
            model_name='sexworker',
            name='sex_workers_female_15_19',
            field=models.PositiveIntegerField(null=True, verbose_name='female 15 to 19'),
        ),
        migrations.AlterField(
            model_name='sexworker',
            name='sex_workers_female_20_24',
            field=models.PositiveIntegerField(null=True, verbose_name='female 20 to 24'),
        ),
        migrations.AlterField(
            model_name='sexworker',
            name='sex_workers_female_25_29',
            field=models.PositiveIntegerField(null=True, verbose_name='female 25 to 29'),
        ),
        migrations.AlterField(
            model_name='sexworker',
            name='sex_workers_female_30_34',
            field=models.PositiveIntegerField(null=True, verbose_name='female 30 to 34'),
        ),
        migrations.AlterField(
            model_name='sexworker',
            name='sex_workers_female_35_plus',
            field=models.PositiveIntegerField(null=True, verbose_name='female 35 plus'),
        ),
        migrations.AlterField(
            model_name='sexworker',
            name='sex_workers_male_10_14',
            field=models.PositiveIntegerField(null=True, verbose_name='male 10 to 14'),
        ),
        migrations.AlterField(
            model_name='sexworker',
            name='sex_workers_male_15_19',
            field=models.PositiveIntegerField(null=True, verbose_name='male 15 to 19'),
        ),
        migrations.AlterField(
            model_name='sexworker',
            name='sex_workers_male_20_24',
            field=models.PositiveIntegerField(null=True, verbose_name='male 20 to 24'),
        ),
        migrations.AlterField(
            model_name='sexworker',
            name='sex_workers_male_25_29',
            field=models.PositiveIntegerField(null=True, verbose_name='male 25 to 29'),
        ),
        migrations.AlterField(
            model_name='sexworker',
            name='sex_workers_male_30_34',
            field=models.PositiveIntegerField(null=True, verbose_name='male 30 to 34'),
        ),
        migrations.AlterField(
            model_name='sexworker',
            name='sex_workers_male_35_plus',
            field=models.PositiveIntegerField(null=True, verbose_name='male 35 plus'),
        ),
        migrations.AlterField(
            model_name='stakeholderdirectory',
            name='permanent_employee_female',
            field=models.PositiveIntegerField(null=True, verbose_name='current number of permanent female employees'),
        ),
        migrations.AlterField(
            model_name='stakeholderdirectory',
            name='permanent_employee_male',
            field=models.PositiveIntegerField(null=True, verbose_name='current number of permanent male employees'),
        ),
        migrations.AlterField(
            model_name='stakeholderdirectory',
            name='temporary_employee_female',
            field=models.PositiveIntegerField(null=True, verbose_name='current number of temporary female employees'),
        ),
        migrations.AlterField(
            model_name='stakeholderdirectory',
            name='temporary_employee_male',
            field=models.PositiveIntegerField(null=True, verbose_name='current number of temporary male employees'),
        ),
        migrations.AlterField(
            model_name='stakeholderdirectory',
            name='volunteer_employee_female',
            field=models.PositiveIntegerField(null=True, verbose_name='current number of volunteer female employees'),
        ),
        migrations.AlterField(
            model_name='stakeholderdirectory',
            name='volunteer_employee_male',
            field=models.PositiveIntegerField(null=True, verbose_name='current number of volunteer male employees'),
        ),
        migrations.AlterField(
            model_name='supportgroupsetup',
            name='support_groups',
            field=models.PositiveIntegerField(null=True, verbose_name='number'),
        ),
        migrations.AlterField(
            model_name='synergydevelopmentsector',
            name='employees_reached_female_num',
            field=models.PositiveIntegerField(null=True, verbose_name='female'),
        ),
        migrations.AlterField(
            model_name='synergydevelopmentsector',
            name='employees_reached_male_num',
            field=models.PositiveIntegerField(null=True, verbose_name='male'),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='teachers_female',
            field=models.PositiveIntegerField(null=True, verbose_name='female'),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='teachers_male',
            field=models.PositiveIntegerField(null=True, verbose_name='male'),
        ),
        migrations.AlterField(
            model_name='transgenderindividual',
            name='transgender_num',
            field=models.PositiveIntegerField(null=True, verbose_name='number'),
        ),
        migrations.AlterField(
            model_name='vulnerablepeople',
            name='ovc_female_10_14',
            field=models.PositiveIntegerField(null=True, verbose_name='female 10 to 14'),
        ),
        migrations.AlterField(
            model_name='vulnerablepeople',
            name='ovc_female_15_19',
            field=models.PositiveIntegerField(null=True, verbose_name='female 15 to 19'),
        ),
        migrations.AlterField(
            model_name='vulnerablepeople',
            name='ovc_female_20_24',
            field=models.PositiveIntegerField(null=True, verbose_name='female 20 to 24'),
        ),
        migrations.AlterField(
            model_name='vulnerablepeople',
            name='ovc_female_25_plus',
            field=models.PositiveIntegerField(null=True, verbose_name='female 25 plus'),
        ),
        migrations.AlterField(
            model_name='vulnerablepeople',
            name='ovc_female_less_10',
            field=models.PositiveIntegerField(null=True, verbose_name='female less than 10'),
        ),
        migrations.AlterField(
            model_name='vulnerablepeople',
            name='ovc_male_10_14',
            field=models.PositiveIntegerField(null=True, verbose_name='male 10 to 14'),
        ),
        migrations.AlterField(
            model_name='vulnerablepeople',
            name='ovc_male_15_19',
            field=models.PositiveIntegerField(null=True, verbose_name='male 15 to 19'),
        ),
        migrations.AlterField(
            model_name='vulnerablepeople',
            name='ovc_male_20_24',
            field=models.PositiveIntegerField(null=True, verbose_name='male 20 to 24'),
        ),
        migrations.AlterField(
            model_name='vulnerablepeople',
            name='ovc_male_25_plus',
            field=models.PositiveIntegerField(null=True, verbose_name='male 25 plus'),
        ),
        migrations.AlterField(
            model_name='vulnerablepeople',
            name='ovc_male_less_10',
            field=models.PositiveIntegerField(null=True, verbose_name='male less than 10'),
        ),
    ]
