# Generated by Django 2.0.5 on 2018-06-21 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sourcesofinformation',
            options={'verbose_name_plural': 'Sources of Information'},
        ),
    ]
