# Generated by Django 2.0.4 on 2018-06-28 08:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data_entry', '0002_otherquestion_sources_of_information'),
    ]

    operations = [
        migrations.CreateModel(
            name='PITMEOValidation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('validation_date', models.DateTimeField(auto_now=True)),
                ('validation_status', models.CharField(choices=[('submitted', 'Submitted'), ('needs_review', 'Needs Review'), ('approved', 'Approved')], max_length=15)),
                ('acknowledgement', models.TextField(default='I acknowledge that I have validated this SARF for data accuracy to the best of my ability. \n                             Any necessary corrections were discussed with the stakeholder prior to this approval. \n                  \n                             Please type your initials below as acknowledgement of the above statement', max_length=1200)),
                ('daca_initials', models.CharField(max_length=5)),
                ('validation_comment', models.TextField(blank=True, max_length=300, null=True)),
                ('activity_form', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data_entry.ActivityReportForm')),
                ('validated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterModelOptions(
            name='sourcesofinformation',
            options={'verbose_name_plural': 'Sources of Information'},
        ),
        migrations.AlterField(
            model_name='mobilepopulationtype',
            name='mobile_population_type',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='otherquestion',
            name='sources_of_information',
            field=models.ManyToManyField(to='data_entry.SourcesOfInformation', verbose_name='which sources of         information does your organisation utilize to inform HIV programming and decision making?'),
        ),
        migrations.AlterField(
            model_name='sourcesofinformation',
            name='source',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='supportfield',
            name='area_of_support',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
    ]
