# Generated by Django 2.0.5 on 2018-06-12 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0002_auto_20180612_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stakeholderdirectory',
            name='description_of_organisation',
            field=models.TextField(max_length=1200, verbose_name='Brief description of the organisation (Please describe your         organisation in no more than 250 words)'),
        ),
    ]
