# Generated by Django 2.0.4 on 2018-06-19 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0003_auto_20180619_2351'),
    ]

    operations = [
        migrations.AddField(
            model_name='dacavalidation',
            name='daca_initials',
            field=models.TextField(default='', max_length=1200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dacavalidation',
            name='daca_validation_statement',
            field=models.TextField(max_length=1200),
        ),
        migrations.AlterField(
            model_name='dacavalidation',
            name='validation_comment',
            field=models.TextField(max_length=300),
        ),
    ]
