# Generated by Django 2.0.4 on 2018-07-07 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0004_auto_20180706_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nationalorganisation',
            name='organisation_name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
