# Generated by Django 2.0.4 on 2018-06-19 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0004_auto_20180620_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dacavalidation',
            name='daca_initials',
            field=models.CharField(max_length=5),
        ),
    ]
