# Generated by Django 2.0.5 on 2018-06-18 06:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data_entry', '0004_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='DACAValidation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('validation_date', models.DateTimeField(auto_now=True)),
                ('form_validated', models.BooleanField(verbose_name='The form is valid')),
                ('activity_form', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data_entry.ActivityReportForm')),
                ('validated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
