# Generated by Django 2.0.5 on 2018-06-18 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0005_dacavalidation'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityreportform',
            name='comment',
            field=models.TextField(blank=True, max_length=200, verbose_name='additional comments'),
        ),
        migrations.AddField(
            model_name='stakeholderdirectory',
            name='comment',
            field=models.TextField(blank=True, max_length=200, verbose_name='additional comments'),
        ),
        migrations.AlterField(
            model_name='fundingsource',
            name='funding_amount',
            field=models.PositiveIntegerField(verbose_name='Funding Amount(In Zambian Kwacha)'),
        ),
    ]
