# Generated by Django 2.0.5 on 2018-06-18 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0006_auto_20180618_1054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activityreportform',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='stakeholderdirectory',
            name='comment',
        ),
    ]
