# Generated by Django 2.0.4 on 2018-07-18 04:04

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0006_auto_20180710_0140'),
    ]

    operations = [
        migrations.CreateModel(
            name='StakeholderVerification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval', models.CharField(max_length=10)),
                ('acknowledgement', models.TextField(default=' I verify that this information is complete and correct and that I have not \n    misrepresented any information.', max_length=1200)),
                ('stakeholder_initials', models.CharField(max_length=5, verbose_name='data entry initials')),
                ('activity_form', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data_entry.ActivityReportForm')),
            ],
        ),
        migrations.AlterField(
            model_name='iecmaterial',
            name='localized',
            field=models.BooleanField(default=False, verbose_name='localised'),
        ),
        migrations.AlterField(
            model_name='nationalorganisation',
            name='organisation_name',
            field=models.CharField(max_length=200, unique=True, validators=[django.core.validators.RegexValidator('(?!^\\d+$)^.+$', 'Only alphanumeric characters are allowed and not numbers only.')]),
        ),
    ]
