# Generated by Django 2.0.4 on 2018-06-20 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0007_auto_20180620_0757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dacavalidation',
            name='validation_comment',
            field=models.TextField(max_length=300, null=True),
        ),
    ]
