# Generated by Django 2.0.5 on 2018-06-18 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0007_auto_20180618_1437'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nationalorganisation',
            options={'verbose_name': 'Parent Organisation'},
        ),
    ]
