# Generated by Django 2.0.4 on 2018-07-18 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0008_auto_20180718_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endofyearquestion',
            name='number_of_meetings_daft',
            field=models.PositiveIntegerField(verbose_name='How many DHAC meetings did your organisation attend         this year?'),
        ),
    ]
