# Generated by Django 2.0.5 on 2018-06-18 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0008_auto_20180618_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stakeholderdirectory',
            name='organisation',
            field=models.CharField(max_length=200, verbose_name='organisation/ project'),
        ),
    ]
