# Generated by Django 2.0.5 on 2018-06-19 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0009_auto_20180618_1659'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nationalorganisation',
            options={'verbose_name': 'parent organisation'},
        ),
        migrations.AlterField(
            model_name='stakeholderdirectory',
            name='national_organisation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data_entry.NationalOrganisation', verbose_name='parent organisation'),
        ),
    ]
