# Generated by Django 2.0.5 on 2018-06-19 07:35

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0010_auto_20180619_0552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityreportform',
            name='telephone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='0xxxxxxxxx', max_length=128),
        ),
        migrations.AlterField(
            model_name='stakeholderdirectory',
            name='telephone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='0xxxxxxxxx', max_length=128),
        ),
        migrations.AlterField(
            model_name='stakeholderdirectory',
            name='telephone_number_alternative',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='0xxxxxxxxx', max_length=128),
        ),
    ]
