# Generated by Django 2.0.4 on 2018-07-31 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0010_remove_stakeholderverification_approval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dacavalidation',
            name='validation_comment',
            field=models.TextField(blank=True, max_length=600, null=True, verbose_name='Validation Comment'),
        ),
        migrations.AlterField(
            model_name='dacavalidation',
            name='validation_status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('needs_review', 'Needs Review'), ('approved', 'Approved')], max_length=15, verbose_name='DACA validation status'),
        ),
        migrations.AlterField(
            model_name='pitmeovalidation',
            name='validation_comment',
            field=models.TextField(blank=True, max_length=600, null=True, verbose_name='Validation Comment'),
        ),
        migrations.AlterField(
            model_name='pitmeovalidation',
            name='validation_status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('needs_review', 'Needs Review'), ('approved', 'Approved')], max_length=15, verbose_name='PITMEO validation status'),
        ),
    ]
