# Generated by Django 2.0.4 on 2018-08-02 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0011_auto_20180731_1055'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubheaderLabel1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_entry.ActivityReportForm')),
            ],
        ),
        migrations.CreateModel(
            name='SubheaderLabel2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_entry.ActivityReportForm')),
            ],
        ),
        migrations.CreateModel(
            name='SubheaderLabel3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_entry.ActivityReportForm')),
            ],
        ),
        migrations.CreateModel(
            name='SubheaderLabel4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_entry.ActivityReportForm')),
            ],
        ),
        migrations.CreateModel(
            name='SubheaderLabel5',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_entry.ActivityReportForm')),
            ],
        ),
        migrations.CreateModel(
            name='SubheaderLabel6',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_entry.ActivityReportForm')),
            ],
        ),
        migrations.CreateModel(
            name='SubheaderLabel7',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_entry.ActivityReportForm')),
            ],
        ),
    ]
