# Generated by Django 2.0.5 on 2018-06-19 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0012_auto_20180619_1020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endofyearquestion',
            name='number_of_meetings_paft',
        ),
        migrations.AlterField(
            model_name='otherquestion',
            name='action_plan',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=100, verbose_name='Does you organisation have a current HIV and         AIDS action plan?'),
        ),
    ]
