# Generated by Django 2.0.5 on 2018-06-19 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0012_auto_20180619_1020'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activityreportform',
            options={'verbose_name': 'stakeholder activity report form'},
        ),
    ]
