# Generated by Django 2.0.4 on 2018-08-13 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0013_auto_20180813_1438'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PreventionMessageList',
        ),
        migrations.AlterUniqueTogether(
            name='programactivity',
            unique_together={('ward', 'organisation')},
        ),
    ]
