# Generated by Django 2.0.5 on 2018-06-19 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0013_auto_20180619_1205'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activityreportform',
            options={'verbose_name_plural': 'Stakeholder Activity Report Form (SARF)'},
        ),
        migrations.AlterModelOptions(
            name='stakeholderdirectory',
            options={'verbose_name_plural': 'Stakeholder Directory'},
        ),
    ]
