# Generated by Django 2.0.4 on 2018-08-14 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0014_auto_20180813_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='iecmaterial2',
            name='other_target_audience',
            field=models.CharField(max_length=100, null=True, verbose_name='other'),
        ),
        migrations.AddField(
            model_name='mobilepopulation',
            name='other_mobile_population',
            field=models.CharField(max_length=100, null=True, verbose_name='other'),
        ),
        migrations.AddField(
            model_name='stakeholderdirectory',
            name='other_organisation_target',
            field=models.CharField(max_length=100, null=True, verbose_name='other target groups - please specify'),
        ),
        migrations.AddField(
            model_name='stakeholderdirectory',
            name='other_organisation_type',
            field=models.CharField(max_length=100, null=True, verbose_name='other organisation/ group - please specify'),
        ),
        migrations.AddField(
            model_name='targetgrouppreventionmessage',
            name='other_organisation_target',
            field=models.CharField(max_length=100, null=True, verbose_name='other target groups - please specify'),
        ),
    ]
