# Generated by Django 2.0.5 on 2018-06-19 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0014_auto_20180619_1213'),
        ('data_entry', '0013_auto_20180619_1058'),
    ]

    operations = [
    ]
