# Generated by Django 2.0.4 on 2018-08-21 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0015_auto_20180814_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iecmaterial2',
            name='other_target_audience',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='other'),
        ),
        migrations.AlterField(
            model_name='mobilepopulation',
            name='other_mobile_population',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='other'),
        ),
        migrations.AlterField(
            model_name='stakeholderdirectory',
            name='other_organisation_target',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='other target groups - please specify'),
        ),
        migrations.AlterField(
            model_name='targetgrouppreventionmessage',
            name='other_organisation_target',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='other target groups - please specify'),
        ),
    ]
