# Generated by Django 2.0.4 on 2018-08-23 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0016_auto_20180821_1312'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreventionMessageList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prevention_message', models.CharField(default='', max_length=100, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='stakeholderdirectory',
            name='other_organisation_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='other organisation/ group - please specify'),
        ),
        migrations.AlterUniqueTogether(
            name='targetgrouppreventionmessage',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='targetgrouppreventionmessage',
            name='prevention_message',
        ),
        migrations.AddField(
            model_name='targetgrouppreventionmessage',
            name='prevention_list',
            field=models.ManyToManyField(to='data_entry.PreventionMessageList', verbose_name='prevention messages         conveyed by the program/ activity'),
        ),
    ]
