# Generated by Django 2.0.4 on 2018-08-24 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0017_auto_20180823_1715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='targetgrouppreventionmessage',
            name='prevention_list',
        ),
        migrations.AddField(
            model_name='targetgrouppreventionmessage',
            name='prevention_list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data_entry.PreventionMessageList', verbose_name='prevention messages conveyed by the program/ activity'),
        ),
    ]
