# Generated by Django 2.0.4 on 2018-08-31 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0020_dataetl'),
    ]

    operations = [
        migrations.AddField(
            model_name='stakeholderdirectory',
            name='latitude',
            field=models.CharField(blank=True, help_text='Use decimal degrees format(ie: 28.32282)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='stakeholderdirectory',
            name='longitude',
            field=models.CharField(blank=True, help_text='Use decimal degrees format(ie: -15.38753)', max_length=20, null=True),
        ),
    ]
