# Generated by Django 2.0.4 on 2018-09-11 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0022_auto_20180831_0555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stakeholderdirectory',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='stakeholderdirectory',
            name='longitude',
        ),
        migrations.AlterField(
            model_name='dataetl',
            name='period',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='district',
            name='district_latitude',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='district',
            name='district_longitude',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
