# Generated by Django 2.0.4 on 2018-10-09 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0024_auto_20181008_2237'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dataetl',
            old_name='dataElementID',
            new_name='data_element_id',
        ),
        migrations.RenameField(
            model_name='dataetl',
            old_name='dataElementName',
            new_name='data_element_name',
        ),
        migrations.RenameField(
            model_name='dataetl',
            old_name='orgUnitID',
            new_name='org_unit_id',
        ),
        migrations.RenameField(
            model_name='dataetl',
            old_name='orgUnitName',
            new_name='org_unit_name',
        ),
    ]
