# Generated by Django 2.1.2 on 2018-10-15 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0026_auto_20181012_1032'),
    ]

    operations = [
        migrations.CreateModel(
            name='StakeholderDirectoryStaff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'position',
            },
        ),
        migrations.AddField(
            model_name='stakeholderdirectory',
            name='position_available',
            field=models.ManyToManyField(to='data_entry.StakeholderDirectoryStaff', verbose_name='Please Tick(if position or         equivalent is available in the organisation structure'),
        ),
    ]
