# Generated by Django 2.0.2 on 2018-02-26 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReportDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateTimeField(verbose_name='date of report')),
                ('quarter', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('report_type', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('reporter_name', models.CharField(max_length=100)),
                ('reporter_phone', models.CharField(max_length=50)),
                ('reporter_email', models.CharField(max_length=100)),
            ],
        ),
    ]
