apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
    name: nacmis-ingress
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /
      kubernetes.io/ingress.class: "nginx"
      cert-manager.io/issuer: "letsencrypt-production"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  rules:
  - host: www.nacmis.org.zm
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          serviceName: nacmis-service
          servicePort: 8000
      - path: /static/
        pathType: Prefix
        backend:
          serviceName: nacmis-statics-service
          servicePort: 80
  - host: nacmis.org.zm
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          serviceName: nacmis-service
          servicePort: 8000
      - path: /static/
        pathType: Prefix
        backend:
          serviceName: nacmis-statics-service
          servicePort: 80
  - host: nacmis-data.bluecodeltd.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          serviceName: superset-service
          servicePort: 8088
