resources:
  - storage.yaml
  - deployment.yaml
  - secrets.yaml
  - ingress.yaml
vars:
  - name: postgres-service
    objref:
      kind: Service
      name: postgres-service
      apiVersion: v1
    fieldref:
      fieldpath: metadata.name
  - name: nacmis-service
    objref:
      kind: Service
      name: nacmis-service
      apiVersion: v1
    fieldref:
      fieldpath: metadata.name
  - name: superset-service
    objref:
      kind: Service
      name: superset-service
      apiVersion: v1
    fieldref:
      fieldpath: metadata.name
  - name: redis-service
    objref:
      kind: Service
      name: redis-service
      apiVersion: v1
    fieldref:
      fieldpath: metadata.name
